server:
  port: 10053

spring:
  application:
    name: gateway
  cloud:
    nacos:
      #指定注册中心地址
      discovery:
        server-addr: localhost:8848
      # 配置中心
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true             # 使用服务发现路由
      routes:                       # 路由
      - id: product-gateway         # 设置路由id
        uri: lb://product           # 设置路由的url lb://nacos服务注册名称
        predicates:                 # 路径匹配规则
#          - Host=**.foo.org
#          - Path=/pro/**
          - Method=GET
#          - Header=X-Request-Id, \d+
#          - Query=foo, ba.
#          - Query=baz
#          - Cookie=chocolate, ch.p
#          - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
