server:
  port: 10053

spring:
  application:
    name: gateway
  cloud:
    nacos:
      # 指定注册中心地址
      discovery:
        server-addr: localhost:8848
      # 配置中心
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true             # 使用服务发现路由
      routes:                       # 路由
      - id: product-gateway         # 设置路由id
        uri: lb://product           # 设置路由的url lb://nacos服务注册名称
        predicates:                 # 路径匹配规则
#          - Host=**.foo.org
#          - Path=/pro/**
          - Method=GET
#          - Header=X-Request-Id, \d+
#          - Query=foo
#          - Query=baz
#          - Cookie=chocolate
#          - After=2021-05-12T15:06:06+08:00[Asia/Shanghai]
        filters:                    # 限流
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@hostAddrKeyResolver}' # 用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
              redis-rate-limiter.replenishRate: 1     # 令牌桶每秒填充平均速率
              redis-rate-limiter.burstCapacity: 5     # 令牌桶总容量
  redis:                            # 限流使用
    host: localhost
    port: 6379
    database: 0
