
server:
  port: 10052
spring:
  application:
    name: configure
  cloud:
    nacos:
      #指定注册中心地址
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        #暴露所有web端点
        include: '*'
nacos:
  config:
    server-addr: localhost:8848
  discovery:
    server-addr: localhost:8848